-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : ven. 15 oct. 2021 à 12:04
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `blog`
--

-- --------------------------------------------------------

--
-- Structure de la table `billets`
--

DROP TABLE IF EXISTS `billets`;
CREATE TABLE IF NOT EXISTS `billets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date_creation` date NOT NULL,
  `titre` varchar(255) NOT NULL,
  `contenu` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=46 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `billets`
--

INSERT INTO `billets` (`id`, `date_creation`, `titre`, `contenu`) VALUES
(1, '2021-10-08', 'Chapitre 1', '<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vulputate condimentum fermentum. Nam vitae leo sed mauris faucibus fringilla. Vestibulum eleifend dignissim felis, ut aliquam lorem scelerisque vitae. Vivamus tempor lobortis mauris, ac efficitur augue ullamcorper ac. Ut feugiat vulputate nunc, vitae mattis nunc vehicula eu. Morbi id viverra purus. Mauris viverra dolor hendrerit mi facilisis, vel aliquet sem pellentesque. Maecenas in iaculis felis, ut aliquam turpis. Sed ut purus non tortor porta tempus. Sed tristique aliquet nisl quis laoreet. Vestibulum ultrices, elit vel interdum elementum, tellus nisi luctus orci, pharetra tempor turpis turpis placerat ligula. Pellentesque gravida libero eget interdum maximus. In efficitur sem ex, quis convallis libero dapibus in. Integer condimentum mauris mauris, et hendrerit magna placerat quis. Sed vitae blandit ex.</p>\r\n<p>Nunc vehicula est id lorem pretium, vel elementum metus imperdiet. Praesent convallis maximus odio nec commodo. Cras mattis convallis posuere. Nullam id bibendum ante. Nam blandit ex sapien. Curabitur eu feugiat ligula. Donec a pulvinar ligula.</p>\r\n<p>Curabitur efficitur dui eget vestibulum pharetra. In ultrices tellus tincidunt est lobortis, a accumsan tortor dignissim. Ut hendrerit diam nunc, id pellentesque neque vulputate luctus. Mauris porta at nibh vel posuere. Vivamus eget lacus sapien. Nullam congue, erat vitae ornare ultrices, diam velit tempus nisl, a vulputate mauris dui nec ex. Donec egestas enim et justo venenatis, porttitor vehicula odio cursus. Aenean nunc dolor, ultrices at aliquam nec, ullamcorper et turpis. Fusce porttitor ultricies turpis, varius varius dui interdum a. Suspendisse varius dolor enim, id lobortis nibh pulvinar at. Donec porttitor augue nisi. Quisque sed varius lectus. Phasellus laoreet metus ante. Mauris consequat bibendum cursus.</p>'),
(2, '2021-10-08', 'Chapitre 2', '<p>Donec quis elit vitae dolor ornare commodo. Nam eu varius sem. Nam eget purus in felis viverra consequat. Nam a eros&nbsp;</p>'),
(43, '2021-10-15', 'Chapitre 6', '<p>Praesent ut rutrum neque, ac lobortis ipsum. Sed mollis auctor lacus, vel luctus tellus dapibus ut. Nullam a euismod est, ut euismod dui. Donec accumsan libero sollicitudin iaculis dictum. Vestibulum pellentesque feugiat dui eu sodales. Suspendisse maximus erat eget orci cursus mattis. Sed a sagittis lacus. Aenean feugiat, elit ac accumsan bibendum, ex magna varius nulla, vel blandit est eros et leo. Integer sed tortor convallis, sagittis diam eget, lobortis ante. Nam egestas malesuada metus, ac dapibus nunc mattis sed.</p>\r\n<p>Sed pretium est ut dui consectetur pretium. Nam sed dolor consectetur, congue sapien eu, congue tortor. Duis eget condimentum sem. Integer tristique elit enim, in elementum libero imperdiet id. Fusce ultrices quis massa at imperdiet. Aenean sagittis, augue id ultricies convallis, libero neque tempus metus, at rhoncus mauris justo in augue. Nulla facilisi. Fusce sit amet aliquet massa. Nulla facilisi. Nulla lacinia enim nec ex euismod ornare.</p>\r\n<p>Proin auctor eget eros quis posuere. Nunc non pellentesque odio, sed pellentesque velit. Nulla aliquam lectus justo, id consectetur tellus scelerisque eget. Sed fringilla velit non turpis efficitur, ut volutpat ante imperdiet. Nulla elit lacus, malesuada nec consequat in, gravida convallis ex. Sed id tristique ligula. Ut vitae fermentum tellus.</p>\r\n<p>Praesent fringilla tincidunt feugiat. Quisque vitae semper sem, eget rhoncus neque. Phasellus pretium malesuada mi in vestibulum. Aliquam sapien augue, euismod at lectus quis, finibus tristique purus. Morbi sit amet mattis purus, vel tristique purus. Ut finibus leo eu efficitur dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eleifend felis quam, quis commodo lectus pretium ut. Phasellus congue sed metus in porta. Sed ut posuere erat, et faucibus lacus. Suspendisse non lacus euismod eros egestas facilisis id vitae risus. Integer congue ultricies dui, at efficitur ante hendrerit ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis auctor quam sit amet blandit vulputate. Duis efficitur pharetra ante, quis mollis purus rutrum ut.</p>'),
(44, '2021-10-15', 'Chapitre 8', '<p>Proin viverra, mi a sodales vehicula, velit augue consectetur erat, at convallis nulla neque non enim. In ullamcorper id elit id hendrerit. Duis at sodales neque. Vestibulum finibus mi lacus, a interdum nunc consectetur in. Nunc sollicitudin, lacus nec congue fermentum, nunc dui dapibus mauris, id bibendum turpis magna in nunc. Suspendisse auctor dapibus tortor ac vestibulum. Suspendisse id euismod ante. Aliquam quis ex odio. Vestibulum pharetra accumsan nulla sit amet accumsan. Aliquam at mollis nisl, quis ultrices felis. Praesent ac ultricies elit. Fusce nisl velit, porta vel posuere vitae, rutrum et turpis. Curabitur a vestibulum nibh.</p>\r\n<p>Nulla eu sapien accumsan, dictum enim sit amet, egestas eros. Sed finibus justo in consectetur euismod. Suspendisse at sapien cursus, luctus est quis, lacinia neque. Nam mauris metus, posuere at lorem porta, luctus gravida est. Aliquam sodales lectus commodo leo viverra gravida. Etiam id ullamcorper dui. Praesent tempus tellus dolor, a suscipit lectus aliquam quis. Sed laoreet purus sit amet nisl ullamcorper porttitor. Sed bibendum tellus at varius scelerisque. Integer dictum dolor elit, eu mollis dolor eleifend nec. Aliquam vel eros velit. Nam ornare, enim id semper egestas, lacus libero lacinia arcu, non consequat magna dolor non purus.</p>\r\n<p>Sed tristique tellus ante, quis semper justo eleifend id. Morbi eu felis a magna volutpat pulvinar ac id lacus. Aenean dictum, tortor et vehicula condimentum, sapien est ullamcorper odio, vel ullamcorper diam eros vitae ante. Praesent in dui et eros pellentesque faucibus. Donec blandit mi a aliquet pretium. Nullam ut ultricies nisl, sit amet condimentum est. Integer viverra tristique leo nec feugiat. Aliquam velit diam, ullamcorper in dictum semper, viverra eget arcu. Proin ut velit id lacus aliquet pulvinar. Donec scelerisque urna eu dui blandit rhoncus. Mauris finibus vitae arcu sit amet commodo. Duis vulputate facilisis euismod. Donec vulputate odio a vestibulum efficitur. Cras et orci malesuada, sollicitudin augue sit amet, consectetur tortor. Proin non malesuada est.</p>\r\n<p>Integer tincidunt pharetra ex imperdiet pellentesque. Quisque cursus tellus in tincidunt blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi commodo tempus tellus, non convallis sem tempus ultrices. Nam mattis fringilla arcu ac dictum. Cras bibendum elementum tellus sit amet lobortis. Praesent quam tellus, aliquam sit amet tincidunt ut, suscipit sit amet nisi. Sed dictum dui elit. Praesent vulputate, mi quis semper fringilla, magna augue suscipit lorem, congue tincidunt lorem risus sed mi. Nulla ut nisi id nisl suscipit fermentum.</p>'),
(45, '2021-10-15', 'Chapitre 7', '<p>Est id lorem pretium, vel elementum metus imperdiet. Praesent convallis maximus odio nec commodo. Cras mattis convallis posuere. Nullam id bibendum ante. Nam blandit ex sapien. Curabitur eu feugiat ligula. Donec a pulvinar ligula.</p>\r\n<p>Curabitur efficitur dui eget vestibulum pharetra. In ultrices tellus tincidunt est lobortis, a accumsan tortor dignissim. Ut hendrerit diam nunc, id pellentesque neque vulputate luctus. Mauris porta at nibh vel posuere. Vivamus eget lacus sapien. Nullam congue, erat vitae ornare ultrices, diam velit tempus nisl, a vulputate mauris dui nec ex. Donec egestas enim et justo venenatis, porttitor vehicula odio cursus. Aenean nunc dolor, ultrices at aliquam nec, ullamcorper et turpis. Fusce porttitor ultricies turpis, varius varius dui interdum a. Suspendisse varius dolor enim, id lobortis nibh pulvinar at. Donec porttitor augue nisi. Quisque sed varius lectus. Phasellus laoreet metus ante. Mauris consequat bibendum cursus.</p>\r\n<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vulputate condimentum fermentum. Nam vitae leo sed mauris faucibus fringilla. Vestibulum eleifend dignissim felis, ut aliquam lorem scelerisque vitae. Vivamus tempor lobortis mauris, ac efficitur augue ullamcorper ac. Ut feugiat vulputate nunc, vitae mattis nunc vehicula eu. Morbi id viverra purus. Mauris viverra dolor hendrerit mi facilisis, vel aliquet sem pellentesque. Maecenas in iaculis felis, ut aliquam turpis. Sed ut purus non tortor porta tempus. Sed tristique aliquet nisl quis laoreet. Vestibulum ultrices, elit vel interdum elementum, tellus nisi luctus orci, pharetra tempor turpis turpis placerat ligula. Pellentesque gravida libero eget interdum maximus. In efficitur sem ex, quis convallis libero dapibus in. Integer condimentum mauris mauris, et hendrerit magna placerat quis. Sed vitae blandit ex.</p>'),
(6, '2021-10-09', 'Chapitre 4 ', 'Cras in vehicula dui. Duis vel odio at mi condimentum placerat. Duis a venenatis dolor, nec molestie urna. Suspendisse eget hendrerit metus, sit amet dapibus nisl. Sed dapibus tincidunt tristique. Vestibulum ac luctus justo, eleifend dignissim augue. Proin fermentum elementum elit, at cursus turpis interdum ut. Morbi tristique, orci vitae dapibus aliquet, ex ante cursus massa, at rhoncus erat lorem at orci. Aenean id urna ac purus consequat sodales. Curabitur consequat tempor enim, ut tempor sapien faucibus vitae. Nunc et est vitae metus sollicitudin efficitur. Curabitur aliquam nibh eu nisi viverra condimentum. Sed ut ipsum sed sem rutrum accumsan vitae nec ex.\r\n\r\nVestibulum aliquet tortor placerat tellus mollis, quis porta elit cursus. Nunc sodales sed metus vel rhoncus. Proin scelerisque ante at ante interdum hendrerit. Donec posuere ornare maximus. Aliquam a accumsan tellus, sit amet ultrices urna. Vivamus dignissim tincidunt quam, eget dictum magna molestie in. Nullam id mauris eleifend, aliquet lorem id, lacinia lectus. Nulla turpis libero, posuere nec sem quis, auctor pulvinar magna. Phasellus quam neque, semper ut justo non, ornare pharetra urna. Vivamus interdum, lectus quis aliquam vehicula, nisl erat auctor neque, id vestibulum odio neque et libero. Fusce ullamcorper ante at elementum tincidunt. In eleifend neque risus, quis accumsan augue tincidunt vel.\r\n\r\nDonec nec massa dolor. Cras ac laoreet urna. Fusce ultricies, turpis at dapibus cursus, ligula arcu tristique nisl, sagittis pharetra est mi sit amet elit. Phasellus interdum lectus eget sapien dapibus, eu venenatis mi ultrices. Aenean ullamcorper purus at eros volutpat, sit amet iaculis nisi imperdiet. Phasellus vestibulum dignissim ante, viverra molestie nisi consectetur ut. Sed tristique nec tellus ut condimentum. Mauris nec ex diam. Ut bibendum, purus at posuere fringilla, ante sem tempus odio, a lobortis leo elit id odio. Nullam ante odio, bibendum at diam id, gravida feugiat urna. Pellentesque venenatis augue sit amet mi dignissim, et aliquam nibh gravida. Phasellus at velit felis. Donec eleifend ipsum nec risus rutrum tincidunt. Morbi sed ligula blandit, commodo nunc vel, consectetur lectus.'),
(5, '2021-10-08', 'Chapitre 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam urna sapien, eleifend in turpis sed, mattis efficitur augue. Integer interdum dapibus turpis dignissim scelerisque. Maecenas nec massa ullamcorper, sollicitudin lacus nec, tempus quam. Praesent dictum elit nec lectus dapibus pellentesque. Ut sem nunc, malesuada \r\nNulla in pellentesque velit. Vivamus facilisis scelerisque tempus. Praesent eget massa dignissim, maximus arcu quis, interdum dui. Nulla ultricies imperdiet sem ac ultrices. Phasellus tristique ullamcorper ipsum. Curabitur est leo, fringilla non mi at, finibus interdum mauris. Integer volutpat, ante et dignissim hendrerit, lacus elit consectetur sapien, id porta nisi mi in velit. Morbi eu laoreet nisl. Vestibulum interdum orci ante. In interdum ex eget commodo tempor.\r\n\r\nUt vulputate imperdiet lobortis. Aenean sollicitudin fringilla facilisis. Donec lobortis eget ante tempus faucibus. Quisque mollis, libero vitae mattis ultrices, justo lacus consequat libero, ac luctus diam sem in nulla. Sed nec rutrum mi. Nulla tristique metus eu velit pharetra iaculis. Pellentesque blandit rutrum tincidunt. Aenean fringilla, ante vitae egestas consectetur, sem mi mattis turpis, id rhoncus massa nisi sit amet lectus. Etiam blandit gravida malesuada. Fusce gravida elit vitae fermentum consectetur. Suspendisse varius volutpat mauris ut pellentesque. Sed interdum accumsan nibh sed vestibulum.'),
(7, '2021-10-09', 'Chapitre 5', 'Donec nec massa dolor. Cras ac laoreet urna. Fusce ultricies, turpis at dapibus cursus, ligula arcu tristique nisl, sagittis pharetra est mi sit amet elit. Phasellus interdum lectus eget sapien dapibus, eu venenatis mi ultrices. Aenean ullamcorper purus at eros volutpat, sit amet iaculis nisi imperdiet. Phasellus vestibulum dignissim ante, viverra molestie nisi consectetur ut. Sed tristique nec tellus ut condimentum. Mauris nec ex diam. Ut bibendum, purus at posuere fringilla, ante sem tempus odio, a lobortis leo elit id odio. Nullam ante odio, bibendum at diam id, gravida feugiat urna. Pellentesque venenatis augue sit amet mi dignissim, et aliquam nibh gravida. Phasellus at velit felis. Donec eleifend ipsum nec risus rutrum tincidunt. Morbi sed ligula blandit, commodo nunc vel, consectetur lectus.\r\n\r\nNulla ut leo vel justo elementum luctus. Phasellus scelerisque accumsan arcu, in efficitur tellus egestas mollis. Duis scelerisque fermentum justo, sit amet bibendum erat. Nunc scelerisque, ligula eu congue egestas, nisi elit sagittis justo, vel congue est sem at diam. Sed blandit augue at sem consequat, a pretium tellus tristique. Ut pellentesque tortor vitae aliquet ultrices. Duis auctor luctus viverra. Nulla feugiat quis quam et feugiat. Phasellus ornare quis urna nec lacinia. Duis fermentum dapibus malesuada.\r\n\r\nMorbi posuere felis eget dolor dapibus tempor. Nunc a lobortis nisi, eget molestie ex. Proin at ex non nulla bibendum bibendum a ac tortor. Morbi at molestie eros. Vestibulum feugiat enim sed felis suscipit scelerisque. Nulla feugiat iaculis vulputate. Duis commodo, ante et vehicula cursus, nisl lectus tristique ipsum, vel convallis eros tortor in velit. Aenean quis leo id lorem lobortis molestie non at massa. Phasellus vel turpis mollis, elementum ante non, vestibulum urna. Nullam eget tempus ex. Nulla et dapibus sapien.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
